# Generated by Django 5.2.8 on 2025-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dzyot7mu6/image/upload/v1764589260/default_jekvg4.jpg', upload_to='profile_images/'),
        ),
    ]
